// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Cart struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CartItem struct {
	ID        int64     `json:"id"`
	CartID    int64     `json:"cart_id"`
	ProductID int64     `json:"product_id"`
	Quantity  int32     `json:"quantity"`
	Price     int64     `json:"price"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Category struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Order struct {
	ID          int64        `json:"id"`
	UserID      int64        `json:"user_id"`
	Status      string       `json:"status"`
	Total       int64        `json:"total"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	CancelledAt sql.NullTime `json:"cancelled_at"`
}

type OrderItem struct {
	ID                  int64     `json:"id"`
	OrderID             int64     `json:"order_id"`
	ProductID           int64     `json:"product_id"`
	Quantity            int32     `json:"quantity"`
	UnitPrice           int64     `json:"unit_price"`
	ProductNameSnapshot string    `json:"product_name_snapshot"`
	CreatedAt           time.Time `json:"created_at"`
}

type Payment struct {
	ID                    int64          `json:"id"`
	OrderID               int64          `json:"order_id"`
	Amount                int64          `json:"amount"`
	Status                string         `json:"status"`
	PaymentMethod         sql.NullString `json:"payment_method"`
	ExternalTransactionID sql.NullString `json:"external_transaction_id"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
}

type Product struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Price         int32          `json:"price"`
	IsAvailable   bool           `json:"is_available"`
	CategoryID    int64          `json:"category_id"`
	Sku           string         `json:"sku"`
	Description   sql.NullString `json:"description"`
	ImageUrl      sql.NullString `json:"image_url"`
	StockQuantity int32          `json:"stock_quantity"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type User struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Role         string         `json:"role"`
	Status       string         `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	ResetToken   sql.NullString `json:"reset_token"`
}
